### ISSUE TITLE
handle relative imports

### ISSUE THREAD

**Issue by CJ-Wright** [symbol-management/symbol-exporter#19]
We need this for the tree shaking use case

**Comment by dacamo76** [comment]
Yeah, we should discuss how to handle packages. I think it may be better to handle them at a higher level, leaving  `SymbolFinder` to parse ast nodes and and another (decorator class PackageSymbolFinder ?) that can take filenames and can walk a package hierarchy, passing the files into `SymbolFinder` and aggregating the results in a final symbols for the package.

PackageSymbolFinder can keep the dir hierarchy structure and call `SymbolFinder` for each file, knowing which is `__init__.py` and knowing the the nested level we are in, combining all calls into a final symbols object for the package.

I think separating the logic will help with maintainability and testing.

We can tackle regular packages first, we may also need to take into account namespace packages, [PEP-420](https://www.python.org/dev/peps/pep-0420/#differences-between-namespace-packages-and-regular-packages), where "Portions of namespace packages need not all come from the same directory structure".

**Comment by CJ-Wright** [comment]
Do you see this changing the data model for when we're handling complete packages?

**Comment by dacamo76** [comment]
Not sure, we may not have to.
We could export a single `symbols` for the entire package instead of per module in the package.

So for example numpy would only export a single `symbols` object, where the symbol name would be the external visible symbols users use when using numpy.

Using`numpy.ones` as an example, these are different ways you can import the symbol: `[numpy.ones, numpy.core.ones, numpy.core.numeric.ones]`

Can we just add these three variants to the existing model as keys?
Maybe later we can be smarter and treat them as aliases?
