### ISSUE TITLE
Differentiate between symbols declared in the module and symbols imported from external module and exposed 

### ISSUE THREAD

**Issue by dacamo76** [symbol-management/symbol-exporter#34]
Do we need to differentiate between symbols declared in the module and symbols imported from external module and exposed? i.e do we need to add metadata to express that `xyz` is actually `abc.xyz`?

_Originally posted by @dacamo76 in https://github.com/symbol-management/symbol-exporter/pull/28#discussion_r574930148_

Example test below:

```python
def test_import_adds_symbols():
     # np should be a symbol in the surface area since it could be
     # imported from this code issue #23
     code = """
     import numpy as np
     from abc import xyz as l
     from abc import xyz
     
     z = np.ones(5)
     """
     tree = ast.parse(dedent(code))
     z = SymbolFinder()
     z.visit(tree)
     # TODO: should we add a key in the metadata to say that a symbol is
     #  a reference to another symbol?
     assert z.symbols == {
         "np": {},
         "xyz": {},
         "l": {},
         "z": {"lineno": 4, "symbols_in_volume": {"numpy.ones"}, "type": "constant"},
     }
```

**Comment by CJ-Wright** [comment]
Yes, that metadata will be needed for tree shaking. If we don't have that then we will be missing edges in the graph, I think. I guess a potential answer to that is to build out a test for a tree shaking toy model. This could also be used to warn developers if they are depending on symbols transitively (eg. depending on `numpy.ones` by depending on `foo.ones` where `foo` has a `from numpy import ones` line) which may be considered dangerous/bad practice, since the lib could change the dep structure at anytime and leave a dev high and dry.

**Comment by CJ-Wright** [comment]
This is handled by the import type
