### ISSUE TITLE
Handle self

### ISSUE THREAD

**Issue by CJ-Wright** [symbol-management/symbol-exporter#50]
It seems we're catching `self.*` as its own part of the volume ([example](https://github.com/symbol-management/ast-symbol-table/blob/master/symbols/xpdan/conda-forge/noarch/xpdan-0.8.1-py_1.json#L5509)). While this may be formally correct, we won't find any package supplying that symbol. We most likely need to handle that case specially, either by just handling `self` or by handling the first argument of the method call. I think working with `self` directly is ok in the short term, since that is a very well established norm although any valid var name could be used.

**Comment by dacamo76** [comment]
Thinking of how we could handle it 'correctly' by using the handling first argument of the method.
We can't differentiate between a function or method the way we currently handle it.

Can we just assume it's a method if there are two or more symbols in the `current_symbol_stack` as we walk the tree?

Should we consider adding meta data to the `current_symbol_stack` so we have more context of the outer namespace?

**Comment by CJ-Wright** [comment]
We could look at the previous symbol in the stack and determine if it is a class, I think that is in our metadata. We may have issues with class method and static method decorators, since we might not have enough inspection power to know when those are in play (static methods being the worse of the two).

Ahh, to some extent this is handled by the other issue I put up. Since `self` is handed into the function/method we may be able to write it off as something passed in and therefore not part of the volume or needing inspection. This will limit tree shaking to individual classes, but that is most likely ok, since objects can do all sorts of nasty things to their internal states that tree shaking won't be able to figure out.

**Comment by dacamo76** [comment]
We can not add the arguments of the function to the volume of the function, that probably takes care of issue #51 , but in this case we are using a symbol in the parameter 'self'.

In the general case, if a parameter exposes a symbol in the body of a function or method should it be added as part of the volume unless it is the first parameter in a method.


```python
def run_jobs(self, job_name_class=None):
    num_jobs = self.get_num_jobs()
    return job_name_class.run(num_jobs)

b = someClass()

run_jobs(job_name_class=b)
```

In this case, `self.get_num_jobs ` should not be added to volume, but should `SomeClass.run` be added?
I think so, `SomeClass()` is already in the volume of the module, but we need to know `SomeClass.run` exists in order to safely call `run_jobs`

We will have to somehow get the mapping: `module.b -> SomeClass().run()` which may be a separate issue.

**Comment by CJ-Wright** [comment]
Hmm, I'm not certain. There are many values that `job_name_class` could take on, for instance it could also be a module and could work. It could also be some other thing with `getattr` access that returns a function. In the example you gave there is a definite map between `b` and `someClass` since that is a standard assignment.

**Comment by CJ-Wright** [comment]
Hmm I think I understand this a bit better now, it seems that self is being placed into undeclared symbols, in the case that it is called (for instance with a class with a `__call__` method.
